# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='pertenece_a',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preguntas.Pregunta'),
        ),
    ]
